FROM node:slim

RUN npm install -g eslint eslint-plugin-html eslint-config-standard eslint-plugin-import eslint-plugin-node eslint-plugin-promise eslint-plugin-standard eslint-plugin-vue babel-eslint eslint-config-fagougou-base eslint-config-fagougou --silent
