FROM node:slim

RUN npm install -g eslint@5.16.0 eslint-plugin-html eslint-config-standard eslint-plugin-import eslint-plugin-node          eslint-plugin-promise eslint-plugin-standard eslint-plugin-vue babel-eslint eslint-config-fagougou