FROM node:lts

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone

ADD .npmrc .npmrc

RUN npm config set registry https://red-nexus-repo.fagougou-law.com/repository/npm-group

RUN mkdir -p /app

WORKDIR /app

ONBUILD ADD ["package.json", "package-lock.json", "/tmp/"]

ONBUILD RUN cd /tmp && npm install --production --silent

ONBUILD RUN mv /tmp/node_modules /app/

ONBUILD ADD . .

CMD ["npm", "start"]
