FROM node:lts

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone

RUN mkdir -p /app

WORKDIR /app

ADD .npmrc .npmrc

ONBUILD ADD "package.json" "/tmp/"

ONBUILD RUN cd /tmp && npm install --production --silent

ONBUILD RUN mv /tmp/node_modules /app/

ONBUILD ADD . .

CMD ["npm", "start"]
